### ISSUE TITLE
portFIRST_USER_INTERRUPT_NUMBER should NOT change (master branch is correct, not development)

### ISSUE THREAD

**Issue by baekgaard** [BriscoeTech/Arduino-FreeRTOS-SAMD51#2]
I've been battling some interrupt issues caused by an incorrect IRQ level; it is known for FreeRTOS on Cortex implementations that default IRQ priorities are 0 (highest) which makes it unsafe if you call FreeRTOS calls. I've fixed my own issue by changing the IRQ priority to 3 (or 192 in the CM4 registers) -- but in the process I wondered why the asserts in place would not catch this.

Turns out that I had copied some changes from the development branch, including the portFIRST_USER_INTERRUPT_NUMBER that had changed from 16 to 64.

Setting it to 64 causes the external interrupts (and a few others) to skip the assertion check, since they are in the range of 16 and up, and skipping the check is not correct. The value should, as far as I can tell, remain at 16 -- it is the difference in number of entries set aside for the kernel exceptions (16 in total) to the start of the table that holds the user defined ones.

When my interrupt priorities are wrong at default values, and if I set the portFIRST_USER_INTERRUPT_NUMBER to 64, my program runs for some time until it encounters a timing race condition and then crashes in weird ways. If I set it to 16, I immediately get an assertion error that a FreeRTOS ...FromISR is called with an incorrect (too high) priority.

So please change it back again so that the master remains at 16 also when you merge, thanks :-)

Correct definition should be:

#define portFIRST_USER_INTERRUPT_NUMBER		( 16 )

**Comment by BriscoeTech** [comment]
Hello baekgaard,

Thank you for posting! This is a great find :-). I think I have some time to see if I can track this down.

I was trying to track down some interrupt issues as well and noticed that when trying to map gpio interrupts, it was failing an assert, and I played with portFIRST_USER_INTERRUPT_NUMBER thinking I had "fixed" the issue. In the development branch -> examples folder I made GpioInterrupt_Test.ino to try and replicate the problem when portFIRST_USER_INTERRUPT_NUMBER was 16.

I am wondering if the IRQ priority is actually the problem iv been chasing. Can you post the command you used to changed this register? 

I am also interested to know if you use the portFIRST_USER_INTERRUPT_NUMBER ( 16 ) as well as your IRQ fix does GpioInterrupt_Test.ino work for you without causing an assert?

Im going to spend some time today and see if I can make some headway.

**Comment by BriscoeTech** [comment]
A very late post, but this was fixed in the 8/22/2020 commit, and is in the current v1.3.0.

Thank you baekgaard!
