### ISSUE TITLE
Prioritizing different threads

### ISSUE THREAD

**Issue by TinManAkshay** [BriscoeTech/Arduino-FreeRTOS-SAMD51#7]
Hi - 

[Not an issue, Just a Discussion]

First of all, I wanted to tell these libraries are very-well written and maintained.

1. When I tried a logic from one of your examples codes:
  xTaskCreate(threadA,     "Task A",       256, NULL, tskIDLE_PRIORITY + 2 &Handle_aTask);
  xTaskCreate(threadB,     "Task B",       256, NULL, tskIDLE_PRIORITY +  1, &Handle_bTask);

The code was only running the Thread B, not both threads.

2. And when I tried this:
  xTaskCreate(threadA,     "Task A",       256, NULL, tskIDLE_PRIORITY + 1, &Handle_aTask);
  xTaskCreate(threadB,     "Task B",       256, NULL, tskIDLE_PRIORITY + 1, &Handle_bTask);
  
The code ran both threads without any issues. 

My concern related to the first point is why didn't both threads run? Having a SAMD51 MCU, how many max. threads I can run without worrying about the issues in the performance as well as functionality? Can I have multiple (more than 5) threads which run on "tskIDLE_PRIORITY + 1"?

I'd really appreciate the insights here.

Thanks,
Akshay

**Comment by BriscoeTech** [comment]
Hello TinManAkshay,

If you go and look at the threadA function, you will notice that there is a for loop, and after so many cycles the tread will stop itself from running. If you reset the micro controller, all the treads will be running again at the start, and threadA will eventually stop itself. That was something I wanted to show was an option in the demo. Make sure to connect your serial port right after you reset your board to see the printf statements.

As far as the max number of threads, that depends on what you are doing in each thread, and that is something the programmer will have to figure out for themselves. 

If your functions don't need to do alot of processing, don't have to share hardware resources, do not block for long periods of time, and have the ram for all task stacks, you can have alot of threads running simultaneously. The processor will get shared efficiently amongst all the threads. Only one thread technically runs at a time, but the rtos will allow you to efficiently switch between all the threads so fast it seems like they are all running at the same time. The rtos will figure out the best way to share the 1 processor among all the threads.

Hope this helps! :-)
